import { useMemo, useState } from 'react';
import { Check, RefreshCcw, Timer, X } from 'lucide-react';
import { PageHeading } from '@/components/layout/page-heading';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/field';
import { Progress } from '@/components/ui/progress';

function generateProblems(seed:number){return Array.from({length:10},(_,index)=>{const a=((seed*7+index*11)%24)+2;const kind=index%5;if(kind===0)return{prompt:`${a}²`,answer:a*a};if(kind===1)return{prompt:`${a*5}% of ${a*4}`,answer:a};if(kind===2)return{prompt:`${a}/4 + ${a}/4`,answer:a/2};if(kind===3)return{prompt:`√${a*a}`,answer:a};return{prompt:`${a} × ${a+3}`,answer:a*(a+3)};});}

export default function MentalMathPage(){const[seed,setSeed]=useState(3);const[index,setIndex]=useState(0);const[value,setValue]=useState('');const[result,setResult]=useState<boolean|null>(null);const[score,setScore]=useState(0);const problems=useMemo(()=>generateProblems(seed),[seed]);const problem=problems[index]!;const check=()=>{const correct=Math.abs(Number(value)-problem.answer)<0.0001;setResult(correct);if(correct)setScore((current)=>current+1);};const next=()=>{if(index===9){setSeed((current)=>current+1);setIndex(0);setScore(0);}else setIndex((current)=>current+1);setValue('');setResult(null);};return <div><PageHeading eyebrow="5-minute daily drill" title="Make basic calculation feel invisible." description="Fractions, percentages, powers, roots, scientific notation and estimation — generated from verified arithmetic rules." actions={<Badge variant="success">No calculator</Badge>} /><div className="mx-auto max-w-2xl"><Card><CardContent className="p-6 sm:p-9"><div className="flex items-center justify-between"><span className="data-label">Problem {index+1} / 10</span><span className="flex items-center gap-1.5 text-xs font-semibold text-muted-foreground"><Timer className="h-4 w-4" />Target 30 sec</span></div><Progress className="mt-3" value={(index/10)*100} /><div className="grid min-h-64 place-items-center text-center"><div><p className="font-display text-5xl font-semibold tracking-[-0.06em]">{problem.prompt}</p><p className="mt-3 text-sm text-muted-foreground">Calculate mentally, then type the result.</p></div></div><div className="flex gap-2"><Input inputMode="decimal" value={value} onChange={(event)=>setValue(event.target.value)} onKeyDown={(event)=>{if(event.key==='Enter'&&value&&result===null)check();}} placeholder="Your answer" aria-label="Your answer" disabled={result!==null} /><Button disabled={!value||result!==null} onClick={check}>Check</Button></div>{result!==null?<div className={`mt-4 flex items-center gap-3 rounded-xl p-4 text-sm ${result?'bg-success/[0.07] text-success':'bg-destructive/[0.06] text-destructive'}`}>{result?<Check className="h-4 w-4" />:<X className="h-4 w-4" />}<span className="flex-1 font-semibold">{result?'Correct':`Answer: ${problem.answer}`}</span><Button size="sm" variant="outline" onClick={next}>{index===9?<><RefreshCcw className="h-3.5 w-3.5" />New set</>:'Next'}</Button></div>:null}<p className="mt-5 text-center text-xs text-muted-foreground">Current score: {score} / {index+(result!==null?1:0)}</p></CardContent></Card></div></div>;}
